-- VHDL module instantiation generated by SCUBA Diamond (64-bit) 3.9.0.99.2
-- Module  Version: 5.7
-- Tue Apr 24 09:58:45 2018

-- parameterized module component declaration
component pll
    port (CLKI: in  std_logic; CLKOP: out  std_logic; 
        CLKOS: out  std_logic; CLKOS2: out  std_logic);
end component;

-- parameterized module component instance
__ : pll
    port map (CLKI=>__, CLKOP=>__, CLKOS=>__, CLKOS2=>__);
